### ISSUE TITLE
Add OIDC authentication middleware

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1518]
Prerequisite: #1517 

## Motivation
We don't want to store or maintain users directly on Airy Core. Instead, we want to leverage [Open ID Connect (OIDC)](https://openid.net/connect/) to authenticate users against their custom providers.

### Backend

Users configure authentication mechanisms in the `airy.yaml`. See the [spring docs](https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/oauth2.html) for required OAuth2.0 provider values.

```yaml
...
    auth:
       systemToken: "token-to-be-used-for-non-web-based-api-interactions"
       oidc:
           allowedEmailPatterns: "*@airy.co,grace@example.org,l.ada@example.org"
           provider: "github"
           clientId: "some value"
           clientSecret: "some super secret value"
           ...
```

Config behavior: 

GIVEN that no auth config is provided 
WHEN a request is made to the backend
THEN there is no authentication check

GIVEN that either system token or oidc config is present
WHEN a request is made to the backend
THEN unauthenticated requests should be rejected

GIVEN that oidc config is present
WHEN a browser user opens the authentication route
THEN the oidc connection authentication flow should be started

GIVEN that a browser user is authenticated with OIDC
WHEN that user makes an authenticated request
THEN the `principal` should be available to endpoints (e.g. using the email for the [senderId](https://github.com/airyhq/airy/blob/51c6b2aad533fe8414b699b5c268ba00983dfee2/backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java#L67))
THEN the principal email should be checked against `allowedEmails` for authorization

**TODOs**
- [x] docs!
- [x] Add an `allowedEmailPatterns` config that takes a list of emails or email wildcards
- [x] Add a sender id to the `/messages.send` endpoint
- [x] Implement oidc auth. For now, we will only implement and test the **Github provider** (decide on the auth endpoints and document for the frontend)
- [x] Add a `/users.getProfile` endpoint that returns the current OIDC profile.
- [x] Add a logout endpoint so that the frontend can delete the session 

**Resources:**
- 1h in-depth Oauth2.0 and open id connect https://www.youtube.com/watch?v=996OiexHze0
- Using OIDC with Spring security https://www.baeldung.com/spring-security-openid-connect 
- Spring OAuth 2.0 docs https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/oauth2.html
