### ISSUE TITLE
Open Source checklist

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#17]
Before we can actually open source the repository there's a variety of tasks that **must** be completed:

- [x] Add a license
- [ ] Rewrite the kafka cluster test code as it's now a copy and paste from confluent code
- [ ] Document the data model accurately 
- [ ] attribute springboot.bzl original work 
- [ ] move work in progress from zube to github projects
- [ ] Make sure the endpoints follow the convention `/something.action` 
- [ ] Review topics config configuration
- [ ] Limit the repository's deployment credentials to only the resources it needs
