### ISSUE TITLE
Change the CLI Install for AWS to Terraform 

### ISSUE THREAD

**Issue by armanjindal** [airyhq/airy#3397]
This is an umbrella issue that contains several smaller issues for the larger-scale change in the CLI. The branch associated with the PR will be set to solve the issues here (in this order)

1. [x] Check that the binaries needed are installed #3359 
2. [x] Set up the files for installation in user workspaces #3360 
3. [x] Execute the `install.sh` script to replace the AWS API calls in the `provider.Provision()` #3392 
4. [x] Update the AWS Installation documentation to reflect these changes #3396 
5. [x] Publish and updated docs for Terraform installation that explain the modules #3376

**Comment by armanjindal** [comment]
Fixed in #3404
